import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuIndicator,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
  NavigationMenuViewport,
} from "@/components/ui/navigation-menu";
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="border-b border-lightblue p-4 flex items-center gap-3">
          <img src="img/magescologo.png" alt="Magesco Logo" className="h-12" />
          <h1 className="m-0 text-lg">Magesco Garden and Pool Services</h1>

          <div className="ml-auto flex items-center gap-3">
          <NavigationMenu>
  <NavigationMenuList className="flex gap-3">
    {/* Products */}
    <NavigationMenuItem>
      <NavigationMenuTrigger>Products</NavigationMenuTrigger>
      <NavigationMenuContent className="w-[300px] h-[150px] p-12 text-xs">
        <NavigationMenuLink href="#">Get started by buying high quality and top-notch pool products</NavigationMenuLink>
      </NavigationMenuContent>
    </NavigationMenuItem>

    {/* Services */}
    <NavigationMenuItem>
      <NavigationMenuTrigger>Services</NavigationMenuTrigger>
      <NavigationMenuContent className="w-[300px] h-[150px] p-12 text-xs">
        <NavigationMenuLink href="#">Services</NavigationMenuLink>
      </NavigationMenuContent>
    </NavigationMenuItem>

    {/* About Us */}
    <NavigationMenuItem>
      <NavigationMenuTrigger>About us</NavigationMenuTrigger>
      <NavigationMenuContent className="w-[300px] h-[150px] p-12 text-xs">
        <NavigationMenuLink href="#">About us</NavigationMenuLink>
      </NavigationMenuContent>
    </NavigationMenuItem>

    {/* Contact Us */}
    <NavigationMenuItem>
      <NavigationMenuTrigger>Contact us</NavigationMenuTrigger>
      <NavigationMenuContent className="w-[300px] h-[150px] p-12 text-xs">
        <NavigationMenuLink href="#">Contact us</NavigationMenuLink>
      </NavigationMenuContent>
    </NavigationMenuItem>
  </NavigationMenuList>
</NavigationMenu>



            <Sheet>
              <SheetTrigger><img src="img/cart.jpg" alt="Cart Icon" className="h-6 w-7" /></SheetTrigger>
              <SheetContent>
                <SheetHeader>
                  <SheetTitle>My Cart</SheetTitle>
                  <SheetDescription>Items</SheetDescription>
                </SheetHeader>
              </SheetContent>
            </Sheet>
          </div>
        </header>

        {children}

        <footer className="border-t border-black p-4 text-center mt-2">
          Footer
        </footer>
      </body>
    </html>
  );
}
